### ISSUE TITLE
Prompt Support

### ISSUE THREAD

**Issue by jheusala** [sendanor/cloud-backend#12]
Optional command line interface for services.

* [x] Initial version
* [x] JSON compatible
* [x] Support `undefined`
* [x] Support functions -- see #2
* [ ] Refactor internal commands with a prefix, for example "/exit" or "\exit" instead of "exit"
* [ ] Support variables -- see #1 
* [ ] Unit testing
* [ ] Support events -- see #11
