### ISSUE TITLE
HTTP support

### ISSUE THREAD

**Issue by jheusala** [sendanor/cloud-backend#5]
Support for connecting services using HTTP or HTTPS.

### TODO

* [x] Service as a REST API
* [x] Client for REST API
* [x] Initial long polling support
  * [ ] Full HTTP polling support in the server
    * Currently does not support events, nor really wait anything. (Was implemented before we had event support.)
    * Might not be needed since we have Socket.io support.
  * [x] HTTP polling support in the client
* [x] Documentation
* [ ] Unit testing
