### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by jheusala** [sendanor/cloud-backend#6]
Uniform way to configure backend setup configurations.

### TODO

* [x] Command line argument support
  * [ ] Unify with JSON file structures
* [ ] JSON file support
